### ISSUE TITLE
fix the regex  to match the ionic project

### ISSUE THREAD

**Issue by shivanipitta** [pxblue/login#23]
#### Bug or feature request?
fix the email regex on login home page for angular project
#### What is the expected behavior?
email input in login home page should just accepts in the email format
#### What is the current behavior?
it has the regex that accepts any value in email field
#### What are the steps to reproduce?
1.

#### What is your environment?

 Framework
- [x ] Angular
- [ ] React

 Browser
- [ ] Internet Explorer
- [ ] Safari
- [ ] Chrome
- [ ] Firefox

 Operating System
- [ ] MacOS
- [ ] Windows
- [ ] Other

**Comment by joebochill** [comment]
Unable to reproduce...ionic and angular are using the same regex patterns and both are functioning as expected.
