### ISSUE TITLE
Form Fields Misaligned

### ISSUE THREAD

**Issue by joebochill** [pxblue/login#5]
#### Bug or feature request?
Bug

#### What is the expected behavior?
Form fields should be properly aligned (registration, forgot)

#### What is the current behavior?
Fields are misaligned

#### Environment
Angular

#### Anything else to add?
Need to remove the percentage-based sizing of elements and margins/padding and replace with appropriate use of flex-box

**Comment by joebochill** [comment]
Alignment looks better, but we should be using flexbox directives instead of css for the flexbox properties

**Comment by joebochill** [comment]
See my comment above

**Comment by joebochill** [comment]
Fixed in #8

**Comment by joebochill** [comment]
<img width="503" alt="misaligned" src="https://user-images.githubusercontent.com/29152776/53582187-0130b280-3b4d-11e9-9eec-bbc1d7cf84cf.png">

**Comment by shivanipitta** [comment]
fixed in #12
